In [1]:
import matplotlib.pyplot as plt
import pandas as pd


pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

In [2]:
dataset = pd.read_csv('busan_accommodation_result.csv') 
dataset.head()
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   장소명     210 non-null    object
 1   평점      210 non-null    float64
 2   주소      210 non-null    object
 3   구분      210 non-null    object
 4   카테고리    210 non-null    object
 5   연락처     194 non-null    object
 6   한줄설명    34 non-null     object
 7   리뷰 개수   210 non-null    object
 8   태그      210 non-null    object
 9   가격      210 non-null    object
 10  영업시간    70 non-null     object
 11  리뷰      210 non-null    object
 12  출처      210 non-null    object
dtypes: float64(1), object(12)
memory usage: 21.5+ KB

In [5]:
dataset["리뷰_길이"] = dataset["리뷰"].astype(str).str.len()

In [6]:
dataset.select_dtypes(include="object") \
  .apply(lambda col: col.astype(str).str.len().max())

장소명        24
주소         44
구분          4
카테고리        6
연락처        14
한줄설명       50
리뷰 개수       5
태그        152
가격        390
영업시간        8
리뷰       1987
출처         10
dtype: int64

In [14]:
# 한국어만 남겨두는 전처리
dataset['한줄설명']

0                                                       NaN
1                                                       NaN
2                                                       NaN
3                                                       NaN
4                                                       NaN
5               관광과 비즈니스의 중심지! 라마다앙코르부산역 호텔에서 편안한 휴식을 즐기세요.
6                                                       NaN
7                                                       NaN
8                                                       NaN
9           매력적인 해운대와 가까운 최적의 위치,\n아늑한 객실과 품격있는 서비스를 이용해보세요
10                                                      NaN
11             탁 트인 바다와 화려한 다이아몬드 브릿지 야경과 함께 배가되는 한화리조트 해운대
12                                                      NaN
13       완벽한 바다 전망과 더불어 편안한 객실을 자랑하는 페어필드 바이 메리어트 송도를 경험하세요
14                                                      NaN
15                                                      NaN
16                                                      NaN
17                                                      NaN
18                                                      NaN
19                           부산광역시 남구에 위치한 그랜드모먼트 유스호스텔입니다.
20                                                      NaN
21                                                      NaN
22                                                      NaN
23              - 부산역 KTX 10번출구 도보 5분 / 연결 통로\n- 비대면 셀프 체크인
24                                                      NaN
25                                                      NaN
26                                                      NaN
27                                                      NaN
28                                                      NaN
29                      부산 도심 속 특별한 휴식 ✨쏘타스위트 부산 서면 호텔 입니다.
30                                                      NaN
31                                                      NaN
32                                                      NaN
33                                                      NaN
34                                                      NaN
35                                                      NaN
36                                                      NaN
37                                                      NaN
38         낙동강과 구포대교, 그리고 푸른 대저생태공원을 끼고 있어 환상적인 리버뷰를 자랑합니다.
39             Not LCT.\n𝐀 𝐍𝐞𝐰𝐂𝐙 𝐋𝐂𝐓.\n\nLCT,\n뉴시즈에서 선보입니다.
40       안녕하세요 2022년 4월 29일자로 새롭게 사업주가 변경된 브라운도트 사직야구장점입니다!
41                                                      NaN
42                                                      NaN
43                                                      NaN
44                                                      NaN
45                                                      NaN
46                                                      NaN
47                                                      NaN
48                                    Relax in NewCZ Osiria
49                                                      NaN
50                                                      NaN
51                          부산의 절경을 담은 5성 프리미엄 호텔 윈덤 그랜드 부산
52                                                      NaN
53                                해운대 여행의 시작을 알리며 끝을 달래주는 곳
54                                                      NaN
55                                     WE BRING AQUA TO YOU
56                                                      NaN
57                                                      NaN
58                                                      NaN
59                                                      NaN
60                                                      NaN
61     유니크하고 럭셔리한 스타일과\n특별하고 프라이빗한 공간을 추구하는\n최적의 호텔로 초대합니다.
62                                                      NaN
63                                                      NaN
64                                                      NaN
65                                                      NaN
66                                                      NaN
67                                                      NaN
68                                                      NaN
69                                                      NaN
70                부산 광안리 해변에서 도보로 단 1분 거리에 위치한 오션스테이 호텔입니다.
71                                                      NaN
72                                                      NaN
73                                                      NaN
74       101층 차원이 다른 6성급 호캉스~ 엘시티 레지던스! 객실 지정 및 명품 어메니티 제공!
75                                                      NaN
76                                                      NaN
77                                                      NaN
78             🌊 호텔 마리쏠에서 매 순간을 특별하게 기억하세요.\n부산의 매력에 빠져보세요.
79                                                      NaN
80                                                      NaN
81                                    Life is Full of NewCZ
82                                                      NaN
83                                                      NaN
84                                                      NaN
85                                                      NaN
86                                                      NaN
87                                                      NaN
88                                                      NaN
89                                                      NaN
90                부산 영도의 랜드마크 호텔노스하버는 2021년8월에 리모델링한 고품격 호텔
91                                                      NaN
92                                                      NaN
93                                                      NaN
94                                                      NaN
95                                                      NaN
96                         광안리 해수욕장 도보 1분거리 위치한 게스트하우스 입니다.
97                                                      NaN
98                                                      NaN
99                                                      NaN
100            휴양과 쇼핑, 교통 등 다양한 인프라를 갖춘 센텀의 중심 센텀프리미어호텔입니다.
101                                                     NaN
102                                                     NaN
103                                                     NaN
104                                                     NaN
105       푸른 부산 바다가 한눈에 펼쳐지는 전 객실 오션뷰\n예약 너무 잘했다고 칭찬 받는 숙소!
106                                                     NaN
107                                                     NaN
108                                                     NaN
109                                                     NaN
110                                                     NaN
111                                                     NaN
112                                                     NaN
113                                                     NaN
114                                                     NaN
115                                                     NaN
116                                  가장 완벽한 휴식 , 아바니 센트럴 부산
117                                                     NaN
118                                                     NaN
119            휴양과 쇼핑, 교통 등 다양한 인프라를 갖춘 센텀의 중심 센텀프리미어호텔입니다.
120                                                     NaN
121                                  가장 완벽한 휴식 , 아바니 센트럴 부산
122                                                     NaN
123                                                     NaN
124      101층 차원이 다른 6성급 호캉스~ 엘시티 레지던스! 객실 지정 및 명품 어메니티 제공!
125                                   우리 숙소는 조용한 휴식형 공간입니다.
126                                                     NaN
127                                                     NaN
128                        광안리 해수욕장 도보 1분거리 위치한 게스트하우스 입니다.
129                                                     NaN
130                                                     NaN
131                                                     NaN
132                                                     NaN
133                                                     NaN
134                                                     NaN
135                                                     NaN
136                                                     NaN
137                                                     NaN
138                                                     NaN
139                                                     NaN
140               부산 광안리 해변에서 도보로 단 1분 거리에 위치한 오션스테이 호텔입니다.
141                                                     NaN
142                                                     NaN
143                                                     NaN
144                                                     NaN
145                                                     NaN
146                                                     NaN
147                                                     NaN
148                                                     NaN
149                                                     NaN
150                                                     NaN
151                                                     NaN
152                                                     NaN
153                                                     NaN
154                                                     NaN
155                                                     NaN
156                                                     NaN
157                                                     NaN
158                                                     NaN
159                                                     NaN
160        낙동강과 구포대교, 그리고 푸른 대저생태공원을 끼고 있어 환상적인 리버뷰를 자랑합니다.
161                                                     NaN
162                                                     NaN
163                                                     NaN
164                                                     NaN
165                                                     NaN
166                                                     NaN
167                                                     NaN
168                                                     NaN
169                                                     NaN
170                                                     NaN
171                                                     NaN
172                                                     NaN
173                                                     NaN
174                                                     NaN
175                                                     NaN
176                                                     NaN
177                                                     NaN
178                                                     NaN
179                                                     NaN
180                                                     NaN
181                                                     NaN
182                                                     NaN
183                                                     NaN
184                                                     NaN
185                                                     NaN
186                                                     NaN
187                                                     NaN
188                                                     NaN
189                                                     NaN
190                                                     NaN
191                                                     NaN
192                                                     NaN
193                                                     NaN
194            부산역에 위치한 호텔포레 더 스파는 도심 속 힐링의 공간을 제공하는 호텔입니다.
195                                                     NaN
196       아름다운 기장 연화리 해녀촌에 있는 호텔입니다. 편안히 쉬실 수 있도록 준비해 놓겠습니다
197                                                     NaN
198                                                     NaN
199                                                     NaN
200                                                     NaN
201            안녕하세요.\n부산 동래 호텔이목은 24년 6월 새롭게 오픈한 동래 호텔입니다.
202                                                     NaN
203                                                     NaN
204                                                     NaN
205                                                     NaN
206                                                     NaN
207                                                     NaN
208                                                     NaN
209                                                     NaN
Name: 한줄설명, dtype: object

In [24]:
import re

def clean_text(text):
    if not isinstance(text, str):
        return text

    # 문자열로 들어간 \n + 실제 공백 문자 모두 제거
    text = re.sub(r'(\\n|\r|\t|\n)', ' ', text)
    text = re.sub(r'\s+', ' ', text)

    # 한글, 영어, 숫자, 기본 문장부호만 유지
    text = re.sub(r'[^가-힣a-zA-Z0-9\s.,!?]', '', text)

    return text.strip()

In [28]:
def preprocess_oneline_desc(df, col="한줄설명"):
    df = df.copy()
    df[col] = df[col].apply(clean_text)
    return df

dataset = preprocess_oneline_desc(dataset)

In [ ]:
dataset['한줄설명']
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   장소명     210 non-null    object
 1   평점      210 non-null    float64
 2   주소      210 non-null    object
 3   구분      210 non-null    object
 4   카테고리    210 non-null    object
 5   연락처     194 non-null    object
 6   한줄설명    34 non-null     object
 7   리뷰 개수   210 non-null    object
 8   태그      210 non-null    object
 9   가격      210 non-null    object
 10  영업시간    70 non-null     object
 11  리뷰      210 non-null    object
 12  출처      210 non-null    object
dtypes: float64(1), object(12)
memory usage: 21.5+ KB

In [33]:
dataset['영업시간']
mask = dataset['영업시간'].str.contains('오픈', na=False)
subset = dataset[mask]
subset[['장소명', '영업시간']]

                  장소명      영업시간
8           마티에오시리아호텔  08:00 오픈
36              와이컬렉션  09:00 오픈
46    엘시티레지던스 더바인 해운대  09:00 오픈
48      뉴시즈 오시리아 레지던스  09:00 오픈
61  베스트루이스해밀턴호텔 오션테라스  11:00 오픈
78         마리쏠by해운대비치  10:00 오픈
81       뉴시즈 해운대 레지던스  09:00 오픈
91               젬스테이  09:00 오픈
98     오데이즈 오시리아 레지던스  09:00 오픈

In [36]:
edit_df = subset[['영업시간']].copy()

In [37]:
opening_hours1 = [
    {'day': '화', 'hours': '08:00 ~ 22:00'},
    {'day': '수', 'hours': '08:00 ~ 22:00'},
    {'day': '목', 'hours': '08:00 ~ 22:00'},
    {'day': '금', 'hours': '08:00 ~ 22:00'},
    {'day': '토', 'hours': '08:00 ~ 22:00'},
    {'day': '일', 'hours': '08:00 ~ 22:00'},
    {'day': '월', 'hours': '08:00 ~ 22:00'},
    ]

opening_hours2 = [
    {'day': '화', 'hours': '09:00 ~ 02:00'},
    {'day': '수', 'hours': '09:00 ~ 02:00'},
    {'day': '목', 'hours': '09:00 ~ 02:00'},
    {'day': '금', 'hours': '09:00 ~ 02:00'},
    {'day': '토', 'hours': '09:00 ~ 02:00'},
    {'day': '일', 'hours': '09:00 ~ 02:00'},
    {'day': '월', 'hours': '09:00 ~ 02:00'},
    ]

opening_hours3 = [
    {'day': '화', 'hours': '09:00 ~ 22:00'},
    {'day': '수', 'hours': '09:00 ~ 22:00'},
    {'day': '목', 'hours': '09:00 ~ 22:00'},
    {'day': '금', 'hours': '09:00 ~ 22:00'},
    {'day': '토', 'hours': '09:00 ~ 22:00'},
    {'day': '일', 'hours': '09:00 ~ 22:00'},
    {'day': '월', 'hours': '09:00 ~ 22:00'},
    ]


opening_hours4 = [
    {'day': '화', 'hours': '11:00 ~ 20:00'},
    {'day': '수', 'hours': '11:00 ~ 20:00'},
    {'day': '목', 'hours': '11:00 ~ 20:00'},
    {'day': '금', 'hours': '11:00 ~ 20:00'},
    {'day': '토', 'hours': '11:00 ~ 20:00'},
    {'day': '일', 'hours': '11:00 ~ 20:00'},
    {'day': '월', 'hours': '11:00 ~ 20:00'},
    ]

opening_hours5 = [
    {'day': '화', 'hours': '10:00 ~ 22:00'},
    {'day': '수', 'hours': '10:00 ~ 22:00'},
    {'day': '목', 'hours': '10:00 ~ 22:00'},
    {'day': '금', 'hours': '10:00 ~ 22:00'},
    {'day': '토', 'hours': '10:00 ~ 22:00'},
    {'day': '일', 'hours': '10:00 ~ 22:00'},
    {'day': '월', 'hours': '10:00 ~ 22:00'},
    ]


opening_hours6 = [
    {'day': '화', 'hours': '09:00 ~ 23:00'},
    {'day': '수', 'hours': '09:00 ~ 23:00'},
    {'day': '목', 'hours': '09:00 ~ 23:00'},
    {'day': '금', 'hours': '09:00 ~ 23:00'},
    {'day': '토', 'hours': '09:00 ~ 23:00'},
    {'day': '일', 'hours': '09:00 ~ 23:00'},
    {'day': '월', 'hours': '09:00 ~ 23:00'},
    ]

In [38]:
edit_df.loc[edit_df.index[0], '영업시간'] = opening_hours1
edit_df.loc[edit_df.index[1], '영업시간'] = opening_hours2
edit_df.loc[edit_df.index[2], '영업시간'] = opening_hours3 
edit_df.loc[edit_df.index[3], '영업시간'] = opening_hours3
edit_df.loc[edit_df.index[4], '영업시간'] = opening_hours4
edit_df.loc[edit_df.index[5], '영업시간'] = opening_hours5
edit_df.loc[edit_df.index[6], '영업시간'] = opening_hours3
edit_df.loc[edit_df.index[7], '영업시간'] = opening_hours6
edit_df.loc[edit_df.index[8], '영업시간'] = opening_hours3

In [39]:
dataset.loc[edit_df.index, '영업시간'] = edit_df['영업시간']

In [46]:
dataset['영업시간']
mask = dataset['영업시간'].str.contains('까지', na=False)
subset = dataset[mask]
subset[['장소명', '영업시간']]

                 장소명      영업시간
41          오션더포인트호텔  12:00 까지
47         더반호텔 해운대점  12:00 까지
66        해운대영무파라드호텔  11:00 까지
75            아크블루호텔  12:00 까지
79      에이치에비뉴 광안해변점  12:00 까지
136  엘시티레지던스 더바인 해운대  22:00 까지
142        더반호텔 해운대점  12:00 까지
147            리자인호텔  12:00 까지
149             젬스테이  23:00 까지
161       영도마리노오토캠핑장  18:00 까지
173          대성관온천호텔  20:30 까지

In [47]:
edit_df = subset[['영업시간']].copy()

In [48]:
opening_hours1 = [
    {'day': '화', 'hours': '16:00 ~ 12:00'},
    {'day': '수', 'hours': '16:00 ~ 12:00'},
    {'day': '목', 'hours': '16:00 ~ 12:00'},
    {'day': '금', 'hours': '16:00 ~ 12:00'},
    {'day': '토', 'hours': '16:00 ~ 12:00'},
    {'day': '일', 'hours': '16:00 ~ 12:00'},
    {'day': '월', 'hours': '16:00 ~ 12:00'},
    ]

opening_hours2 = [
    {'day': '화', 'hours': '15:00 ~ 12:00'},
    {'day': '수', 'hours': '15:00 ~ 12:00'},
    {'day': '목', 'hours': '15:00 ~ 12:00'},
    {'day': '금', 'hours': '15:00 ~ 12:00'},
    {'day': '토', 'hours': '15:00 ~ 12:00'},
    {'day': '일', 'hours': '15:00 ~ 12:00'},
    {'day': '월', 'hours': '15:00 ~ 12:00'},
    ]

opening_hours3 = [
    {'day': '화', 'hours': '16:00 ~ 11:00'},
    {'day': '수', 'hours': '16:00 ~ 11:00'},
    {'day': '목', 'hours': '16:00 ~ 11:00'},
    {'day': '금', 'hours': '16:00 ~ 11:00'},
    {'day': '토', 'hours': '16:00 ~ 11:00'},
    {'day': '일', 'hours': '16:00 ~ 11:00'},
    {'day': '월', 'hours': '16:00 ~ 11:00'},
    ]

opening_hours4 = [
    {'day': '화', 'hours': '09:00 ~ 22:00'},
    {'day': '수', 'hours': '09:00 ~ 22:00'},
    {'day': '목', 'hours': '09:00 ~ 22:00'},
    {'day': '금', 'hours': '09:00 ~ 22:00'},
    {'day': '토', 'hours': '09:00 ~ 22:00'},
    {'day': '일', 'hours': '09:00 ~ 22:00'},
    {'day': '월', 'hours': '09:00 ~ 22:00'},
    ]

opening_hours5 = [
    {'day': '화', 'hours': '18:00 ~ 12:00'},
    {'day': '수', 'hours': '18:00 ~ 12:00'},
    {'day': '목', 'hours': '18:00 ~ 12:00'},
    {'day': '금', 'hours': '18:00 ~ 12:00'},
    {'day': '토', 'hours': '18:00 ~ 12:00'},
    {'day': '일', 'hours': '18:00 ~ 12:00'},
    {'day': '월', 'hours': '18:00 ~ 12:00'},
    ]


opening_hours6 = [
    {'day': '화', 'hours': '09:00 ~ 23:00'},
    {'day': '수', 'hours': '09:00 ~ 23:00'},
    {'day': '목', 'hours': '09:00 ~ 23:00'},
    {'day': '금', 'hours': '09:00 ~ 23:00'},
    {'day': '토', 'hours': '09:00 ~ 23:00'},
    {'day': '일', 'hours': '09:00 ~ 23:00'},
    {'day': '월', 'hours': '09:00 ~ 23:00'},
    ]



opening_hours7 = [
    {'day': '화', 'hours': '09:00 ~ 18:00'},
    {'day': '수', 'hours': '09:00 ~ 18:00'},
    {'day': '목', 'hours': '09:00 ~ 18:00'},
    {'day': '금', 'hours': '09:00 ~ 18:00'},
    {'day': '월', 'hours': '09:00 ~ 18:00'},
    ]

opening_hours8 = [
    {'day': '화', 'hours': '05:00 ~ 20:30'},
    {'day': '수', 'hours': '05:00 ~ 20:30'},
    {'day': '목', 'hours': '05:00 ~ 20:30'},
    {'day': '금', 'hours': '05:00 ~ 20:30'},
    {'day': '토', 'hours': '05:00 ~ 20:30'},
    {'day': '일', 'hours': '05:00 ~ 20:30'},
    {'day': '월', 'hours': '05:00 ~ 20:30'},
    ]

In [49]:
edit_df.loc[edit_df.index[0], '영업시간'] = opening_hours1
edit_df.loc[edit_df.index[1], '영업시간'] = opening_hours2
edit_df.loc[edit_df.index[2], '영업시간'] = opening_hours3
edit_df.loc[edit_df.index[3], '영업시간'] = opening_hours1
edit_df.loc[edit_df.index[4], '영업시간'] = opening_hours1
edit_df.loc[edit_df.index[5], '영업시간'] = opening_hours4
edit_df.loc[edit_df.index[6], '영업시간'] = opening_hours2
edit_df.loc[edit_df.index[7], '영업시간'] = opening_hours5
edit_df.loc[edit_df.index[8], '영업시간'] = opening_hours6
edit_df.loc[edit_df.index[9], '영업시간'] = opening_hours7
edit_df.loc[edit_df.index[10], '영업시간'] = opening_hours8

In [50]:
dataset.loc[edit_df.index, '영업시간'] = edit_df['영업시간']

In [52]:
dataset.head()

,장소명,평점,주소,구분,카테고리,연락처,한줄설명,리뷰 개수,태그,가격,영업시간,리뷰,출처
0,롯데호텔 부산,4.3,부산 부산진구 가야대로 772,숙박업체,호텔,051-810-1000,NaN,116개,"['#2인실', '#가족실', '#물놀이', '#비즈니스호텔', '#사우나', '#실외수영장', '#연회장', '#이동약자접근', '#조식서비스', '#호캉스']","{'룸타입슈페리어 더블 (Superior Double)': '205,700원', '룸타입슈페리어 트윈 (Superior twin)': '205,700원', '룸타입디럭스 더블 (Deluxe Double)': '229,900원', '룸타입디럭스 트윈 (Deluxe Twin)': '229,900원'}",24시간 영업,"['롯데호텔 알바한사람입니다 저도 일을 잘 한 편은 아니지만 , 정말 잘못된 체계라고 생각합니다 . 정직원을 뽑으시던지 계약직을 쓰시던지 알바를 시키면서 계약직을 원하시면 어떻게하자는건지 모르겠습니다 일을 알려주지도 않고 알아서 다 하기를 바라는 신기한 상황을 처음보아 후기를 남깁니다. 알바생을 진짜 직원인것처럼 부려 먹는 신기한 연회장,호텔입니다 ', '연회했는데 직원들이 센스가 하나도 없어서, 쓰레기통 가져다달라, 뜨거운물 가져다달라, 하나하나 말을 해야 겨우 챙겨주고, 서비스는 별1개도 아깝습니다. ', '서면 중심부에 있어서 교통도 편리하고 근처에 맛집도 많아서 좋아요. 호텔은 오래되었지만 관리가 잘되어 있어서 괜찮았어요. 저녁에 실외 수영장도 라이트업 되어서 예뻤고 사진찍기 좋아요. 실내 수영장은 수영하기 좋구요. 라운지 음식도 맛있고 라세느 조식도 맛있어요. 또, 직원분들이 진짜 친절하셔서 좋았어요. ']",카카오맵(2025)
1,시그니엘 부산,4.1,부산 해운대구 달맞이길 30,숙박업체,호텔,051-922-1000,NaN,186개,"['#물놀이', '#사우나', '#야외테라스', '#오션뷰', '#조식서비스', '#호캉스']","{'룸타입그랜드 디럭스 더블 미포하버뷰': '350,900원', '룸타입프리미어 더블 시티뷰': '350,900원', '룸타입프리미어 트윈 미포하버뷰': '399,300원', '룸타입프리미어 패밀리 트윈': '435,600원'}",NaN,"['룸이랑 객실 상태는 완전 좋았고 조식과 주차는 그저 그랬습니다 위치도 좋아서 어디가든지 금방 갈수 있어 좋아요 ', '로비. 엘베 동선과 분위기 어수선. 조식과 인피니티풀 룸 view 좋음. 라운지 협소. 조식 동선이 긴데도불구. 조식과 인피니티풀, 로케이션 때문에 오는듯! 재방문의사 있음. ', '서울 시그니엘 대비 너무 별로임 체크인도 사람 많아서 바글바글... 욕조 물이 안빠지고 이런 일이 자주 있는 듯? 테이블도 까져있고 고급스러운 맛이 없음 ']",카카오맵(2025)
2,신라스테이 해운대,3.6,부산 해운대구 해운대로570번길 46,숙박업체,호텔,051-912-9000,NaN,197개,"['#2인실', '#가족실', '#비즈니스룸', '#비즈니스호텔', '#연회장', '#오션뷰', '#조식서비스', '#호캉스']","{'룸타입[룸온니]스탠다드 더블 시티뷰': '132,165원', '룸타입[룸온니]스탠다드 트윈 시티뷰': '132,165원', '룸타입[룸온니]스탠다드 패밀리 트윈 시티뷰': '132,165원', '룸타입[룸온니]디럭스 더블 시티뷰': '141,955원'}",NaN,"['방에서 욕실을 관람할 수 있도록 벽이 유리벽을 두고 옆으로 열리는 점에서 1차로 놀라고, 전화 쓰는 법이나 화장실 물 내리는 버튼 등등 사소한 것 하나하나 전부 영어로 적어놓고 실내 금연 표시 만큼은 오해없길 바라는 듯 한글로 한번 더 적는게 약간 재섭게 보였는데 침구가 깨끗하고 푹신했던데다 조식 뷔페 직원들이 친절하고 음식이 맛있었어서 5점 남깁니다. ', '업글 해주셔서 주니어 스위트에 들어갔어요 개인적으로 신라스테이는 기대 없이 가는 숙소인데, 주니어 스위트 객실은 좋았어요 ', '해운대 해수욕장 근처 가성비 호텔 해수욕장, 해운대 전통시장 가깝고 좋아요 신라리워즈 포인트 차곡차곡 쌓는중... ']",카카오맵(2025)
3,파크하얏트 부산,4.4,부산 해운대구 마린시티1로 51,숙박업체,호텔,051-990-1234,NaN,178개,"['#사우나', '#실외수영장', '#오션뷰', '#이동약자접근', '#조식서비스', '#호캉스']","{'룸타입스탠다드 (1킹)': '352,000원', '룸타입디럭스 (1킹)': '376,200원', '룸타입디럭스 패밀리 트윈': '376,200원'}",NaN,"['부산 호텔중에 뷰 1등입니다 호텔 리어분들 서비스 너무 좋구요 친절하십니다 조식은 솔직히 아쉬웠습니다 전체적으로나 베이커리류나 시그니엘에 밀리는 편이었습니다만 나쁘지 않았습니다 호텔 규모가 생각보다 작았지만 불편함은 없었습니다 다음에 또 묵을 예정입니다 ', '내 댓글 삭제되었네 왜 지우노 최악 불친절 싸가지 호구되는곳 글 지우면 또 남긴다. ', '다들 너무 친절하시고 객실도 꽤 넓어 좋았습니다 부산에 많은 호텔이 있지만 재방문하고 싶은 호텔 중 하나입니다 위치가 조금 아쉽지만 호캉스 하기엔 충분히 만족스럽네요 ']",카카오맵(2025)
4,그랜드조선 부산,4.3,부산 해운대구 해운대해변로 292,숙박업체,호텔,051-922-5000,NaN,178개,"['#2인실', '#물놀이', '#사우나', '#오션뷰', '#이동약자접근', '#조식서비스', '#호캉스']","{'룸타입슈페리어 시티 더블': '237,600원', '룸타입디럭스 시티 트윈': '231,660원', '룸타입디럭스 시티 킹': '231,660원'}",NaN,"['침구류 좋음 직원들 친절 오션뷰 좋음 복도 방음은 안됨 ', '주차장 들어가는 입구가 너무 협소했지만 아기용품 대여가 많이 돼서 좋았어요.! ', '객실 수에 비해 엘리베이터가 적다. 수영장 크기에 비해 사람이 많다. ']",카카오맵(2025)

In [54]:
# 저장
dataset.to_csv(
    "./final/stay_crawling.csv",
    index=False,
    encoding="utf-8-sig"
)