In [2]:
import pandas as pd

In [3]:
df_tour = pd.read_csv('data/dataset.csv', encoding='cp949')

In [4]:
df_tour.head()

,Country Name,Country Initials,City,Package_Id,Package Title,Duration,Departure City,Departure Date,Places to Visit,Price
0,대한민국,KOR,강릉,DWPS00TC14,"동해~정동진 해안선열차, 고추장만들기체험, 안목항, 정동진 당일 여행",0박 1일,서울,2018.08.31,"정동진,안목항커피거리,고추장만들기","32,000"
1,대한민국,KOR,강릉,DWPS00TC14,"동해~정동진 해안선열차, 고추장만들기체험, 안목항, 정동진 당일 여행",0박 1일,서울,2018.08.24,"정동진,안목항커피거리,고추장만들기","32,000"
2,대한민국,KOR,강릉,DWPS00TC14,"동해~정동진 해안선열차, 고추장만들기체험, 안목항, 정동진 당일 여행",0박 1일,서울,2018.08.25,"정동진,안목항커피거리,고추장만들기","32,000"
3,대한민국,KOR,강릉,DWPS00TC14,"동해~정동진 해안선열차, 고추장만들기체험, 안목항, 정동진 당일 여행",0박 1일,서울,2018.08.26,"정동진,안목항커피거리,고추장만들기","32,000"
4,대한민국,KOR,강릉,DWPS00TC14,"동해~정동진 해안선열차, 고추장만들기체험, 안목항, 정동진 당일 여행",0박 1일,서울,2018.08.28,"정동진,안목항커피거리,고추장만들기","32,000"

In [5]:
df_tour.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23359 entries, 0 to 23358
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country Name      23359 non-null  object
 1   Country Initials  23359 non-null  object
 2   City              23358 non-null  object
 3   Package_Id        23333 non-null  object
 4   Package Title     23359 non-null  object
 5   Duration          23275 non-null  object
 6   Departure City    15330 non-null  object
 7   Departure Date    23359 non-null  object
 8   Places to Visit   23359 non-null  object
 9   Price             15330 non-null  object
dtypes: object(10)
memory usage: 1.8+ MB

In [6]:
df_tour['Package Title'].str.len().describe()

count    23359.000000
mean        31.779443
std         21.091463
min          1.000000
25%         12.000000
50%         32.000000
75%         45.000000
max        115.000000
Name: Package Title, dtype: float64

In [7]:
df_tour['Departure Date'] = pd.to_datetime(df_tour['Departure Date'], format='%Y.%m.%d', errors='coerce')
year_counts = df_tour['Departure Date'].dt.year.value_counts().sort_index()

print(year_counts)

Departure Date
2010.0        1
2011.0        3
2012.0        4
2013.0       25
2014.0      500
2015.0     2076
2016.0     2158
2017.0     2470
2018.0    15047
2019.0        5
2080.0        1
Name: count, dtype: int64

In [8]:
df_tour[df_tour['Departure Date'].dt.year == 2080]

,Country Name,Country Initials,City,Package_Id,Package Title,Duration,Departure City,Departure Date,Places to Visit,Price
12835,대한민국,KOR,청도,c8033e0bacf1a86b,경북 청도 당일치기,5일,NaN,2080-03-11,"우리집,웃음 건강 센터 철가방 극장,청도읍성,혼신지,우리명품한우,청도프로방스포토랜드...",NaN

In [10]:
df_ko_template = pd.read_excel('./data/ko_template.xlsx')

In [11]:
df_ko_template.head()

,type,city,title,start date,start time,end date,place
0,관광지,전라남도,‘봄의 왈츠’ 촬영지,NaN,NaN,NaN,전라남도 완도군 청산면 청산로 136
1,관광지,전라남도,‘서편제’ 촬영지,NaN,NaN,NaN,전라남도 완도군 청산면 당락리
2,관광지,강원도,㈜강원심층수,NaN,NaN,NaN,강원도 고성군 죽왕면 심층수길 124-19
3,관광지,강원도,㈜그래미 발명역사관,NaN,NaN,NaN,강원도 철원군 갈말읍 갈말로 32-30
4,관광지,제주도,㈜제주사랑 농수산,NaN,NaN,NaN,제주특별자치도 제주시 구좌읍 행원로13길 67